### ISSUE TITLE
Bullet point indentation levels larger than 5 cause PPspliT to fail

### ISSUE THREAD

**Issue by mueslo** [maxonthegit/PPspliT#13]
PPSpliT version 1.27
Tested with Office 2021 / Office 2019

![image](https://user-images.githubusercontent.com/847751/190515366-56621e64-1595-4c74-ba51-29a306577884.png)

Inspecting the the stage at which the animation splitting fails, it seems to always stop just before bullet points with a certain amount of indentation. Unindenting them by one removes the error, so it seems that PPSpliT can't deal with indentation level of 6 or larger.

**Comment by jwsimpkins4** [comment]
Just a quick note to say I *just* experienced this same error myself (integer not in the valid range of 0 to 5), after downloading and trying the tool. It wouldn't do the whole PPT (a presentation created by someone else and given to me for importing into ProPresenter). I had to go one by one through the slides and just split the "current" slide each time (and manually duplicate/edit slides that it failed for). So glad you reported this error and also figured out the cause! I hope it can be resolved (or workarounds established). Thanks

**Comment by maxonthegit** [comment]
Thank you for reporting.
I confirm that processing text paragraphs with an indentation level higher than 5 causes PPspliT to fail. In turn, this is caused by an intrinsic limitation in the way PowerPoint's VBA implements the [```IndentLevel``` property](https://learn.microsoft.com/en-us/office/vba/api/powerpoint.textrange.indentlevel):
> Returns or sets the indent level for the specified text as an integer from 1 to 5, where 1 indicates a first-level paragraph with no indentation.

For the sake of completeness, it can be easily checked that PowerPoint seems to internally assume that anything different from static paragraph formatting should use a maximum indentation level of 5. For example, per-paragraph animations by default can iterate over at most level-5 paragraphs (but this can be easily worked around by manually making animation steps for more indented paragraphs click-triggered):
<img width="296" alt="image" src="https://user-images.githubusercontent.com/771877/191106354-c0bafbb5-229c-41bd-856d-2faafdf2cca6.png">
Most likely, the underlying assumption is that further indented paragraphs are not expected to be common (text readability can be impaired by such a deep structure).

Reworking paragraph processing to avoid incurring this issue is not obvious, so for the moment you can assume this is a limitation of PPspliT. I will probably consider adding this to the list of known limitations later on.

**Comment by mueslo** [comment]
I understand, but it would be good to detect this and issue an explicit warning, instead of simply delivering the current cryptic error message.

**Comment by maxonthegit** [comment]
Please check again this issue against PPspliT 2.2: since the method used to handle text paragraph effects has completely changed in the 2.x series, deeply nested text structures should now be supported.
At least, regression test confirm so.
Happy new year!

**Comment by maxonthegit** [comment]
Closing as completed.
