### ISSUE TITLE
Text highlight colour not animated

### ISSUE THREAD

**Issue by mueslo** [maxonthegit/PPspliT#17]
I have an animation step where some text with (non-transparent) text highlight appears.

In the PPspliT-ed output (as of the v2 rewrite), while the text is transparent before the animation step, the text highlight is not. This means that before that PDF page, you see a block of text highlight colour.

Example (animated text with turquoise highlight colour): 
![grafik](https://user-images.githubusercontent.com/847751/228610407-fff3f241-dd1a-4dd1-ae36-cd31a68d6b7d.png)

**Comment by maxonthegit** [comment]
I confirm the behavior you are reporting, thank you.

Differently from 1._x_ releases, where animated text paragraphs were processed by producing multiple copies of the same paragraph (and in some rare cases text formatting failed to be preserved - e.g., graphical bullets), handling text animations now requires clearing paragraphs when they are supposed to be invisible (which ensures highest accuracy of text attributes because paragraphs are actually duplicated together with the containing slides). While this is feasible for most (almost all) text attributes, there seem to be no native ways to hide/clear highlighting using PowerPoint VBA.

Inspired by [this interesting post](https://stackoverflow.com/questions/62019669/unhighlighting-text-and-preserve-all-other-font-settings), in freshly published release 2.4 I have implemented a workaround which should accomplish this goal anyway.
So, you can consider release 2.4 as the one that addresses the issue you have reported.
