### ISSUE TITLE
While converting slide number, generate new number as slide-number.animation-number

### ISSUE THREAD

**Issue by soumitrakp** [maxonthegit/PPspliT#2]
Please keep an option so that while converting slide number, generate new number as <slide-number>.<animation-number>. For example, if slide 12 needs 3 clicks during the animation, it should generate the slide numbers as 12.1, 12.2 and 12.3

**Comment by maxonthegit** [comment]
Implemented in the forthcoming release v1.22.

**Comment by richpixel** [comment]
Thank you for the plugin. This feature doesn't appear to work (Windows version). No matter which option we select in the 'Preserve slide numbers' drop down, it gives us slide numbers that increment by, without outputting sub indices.

**Comment by maxonthegit** [comment]
Hi @richpixel,

I am sorry for this problem. Being a recently implemented feature, I cannot indeed exclude a bug or unsupported case.
It would be great if you could share a minimal sample presentation that triggers the problem (you can use my [contacts](http://www.maxonthenet.altervista.org/contacts.php) page to reach me privately).
Should the bug be confirmed, I will open a new issue to track its analysis.

**Comment by soumitrakp** [comment]
Hi @maxonthegit,
I want to confirm the observation of @richpixel  is correct on MacOS. That is, no matter which option we select in the 'Preserve slide numbers' drop down, it gives us slide numbers that increment by 1, without outputting sub-indices.
Maybe, you should give an example of how to create the slide-number textbox in the original ppt so that PPspliT recognizes the textbox. I tested using a textbox on the master slide that has automatic field <#>. This seems to not work.

**Comment by maxonthegit** [comment]
@soumitrakp, the behavior you are reporting likely indicates that PPspliT is failing in detecting the dynamic text field that contains the slide number, therefore not processing it at all. Unfortunately, such detection is currently limited to special text boxes in slide master layouts that are explicitly meant to act as placeholders for slide numbers. In other words, PPspliT cannot process dynamic slide counters in _any_ text boxes, but only in text boxes that are assigned the function of slide number placeholders in slide masters. This condition is listed among the [known limitations](https://github.com/maxonthegit/PPspliT/blob/master/README.md#known-limitations) (fourth item from last).

Hint: you can skip to _solution to your problem_ below.

Slide number placeholders are usually already present in slide master layouts, like the text box highlighted in blue in the following example:
![Slide number placeholder](https://user-images.githubusercontent.com/771877/91667433-fe799980-eb04-11ea-897a-0cf7b954bca3.png)
However, their visibility needs to be enabled by editing Headers&Footers properties:
![Headers_footers button](https://user-images.githubusercontent.com/771877/91667601-40efa600-eb06-11ea-9d13-62c2932ae119.png)
![Slide number visibility](https://user-images.githubusercontent.com/771877/91667624-5238b280-eb06-11ea-8d0c-1e2dd6b60e0b.png)
Despite being _special_, the contents of this text boxes can be formatted and edited as for any other text boxes, to fit your needs.

In the unlikely case that such box is not present in the slide master layout, it can be added by clicking on the Slide Layout button in the top toolbar:
![Slide layout](https://user-images.githubusercontent.com/771877/91667515-6a5c0200-eb05-11ea-834c-0654dfee61d1.png)

Note that there can be only one such _special_ slide number placeholder in each slide master layout.
Once again, this is the sole and only type of text box in slide master layouts that PPspliT is able to process slide numbers within, the reason being that slide numbers in any other text boxes would be difficult, if not impossible, to detect using VBA.
This should however be a standard usage of Powerpoint, and should be enough to cover all relevant use cases I can think of.

The **solution to your problem** may therefore be to delete any custom text boxes containing slide numbers from your slide master layout(s) and switch to using the standard slide number placeholder instead, remembering to enable its visibility in the Headers&Footers dialog box.

Being that the code base is the same in Windows and MacOS, the same applies to both versions of PPspliT.

If this addresses your request, as well as @richpixel's, I consider this issue as definitively solved. Otherwise, please send a sample presentation that is still confirmed to trigger the failure, as indicated in my previous comment.
