### ISSUE TITLE
Error while splitting

### ISSUE THREAD

**Issue by Taeir** [maxonthegit/PPspliT#3]
First of all, thank you for writing this plugin. I think it is very helpful and should be supported by PowerPoint natively.

When using your tool on the slides of a course I am teaching, I constantly keep getting a fatal error:
![image](https://user-images.githubusercontent.com/668952/86111116-abfd0c00-bac6-11ea-8207-2519a5208208.png)

I have reduced the problem to a single slide, which a simple slide with text boxes, pictures and rectangles. Is any of those not supported by your plugin?
[Cannot split.pptx](https://github.com/maxonthegit/PPspliT/files/4850891/Cannot.split.pptx)
![image](https://user-images.githubusercontent.com/668952/86111770-74429400-bac7-11ea-88bf-172631510f93.png)

Note that if I let PPspliT continue, the resulting slides are correct and as I would expect (at least, I don't notice any problems).

In case shapes like rectangles are not (fully) supported, I would like to ask if it would be possible to add some kind of checkbox to "continue despite any errors" (for future errors as well). For my purposes, the split slides are perfectly fine. However, clicking on "continue" after every error is quite time consuming for a slide deck of 70 slides with many animations on each of them. I do see the error handling delays the slide processing a lot, but as long as it can be done automatic, that would be good enough.

### Versions
PPspliT 1.21
PowerPoint from office 365 (Powerpoint 16)

**Comment by maxonthegit** [comment]
Hi @Taeir and thank you very much for your positive feedback.

Concerning the issue you are experiencing, I have made a couple of tests with two PowerPoint installations:
* one is Microsoft 365, with PowerPoint at release 16.0.12827.20200 (latest at the time of writing), with PPspliT 1.21
* if I remember correctly, the other one is PowerPoint 2006, with PPspliT 1.20

In both cases I am able to successfully split the single slide, as showcased in the following short capture:
![10d95637-fb9b-4876-a0d5-764581e14b65](https://user-images.githubusercontent.com/771877/86176177-e3020a80-bb24-11ea-8a12-d7d5e68b2221.gif)

Please make sure that no applications are interfering with the clipboard while you are splitting. As indicated in the [usage instructions](https://github.com/maxonthegit/PPspliT/blob/master/PPspliT-howto.pdf) as well as in the [README](README.md#usage), this could easily cause the add-in to fail.

Concerning the option to suppress errors, it is something that I have never considered so far (this is also the reason for the _discouraged_ advice in the error dialog box): indeed, errors cause a deviation in normal code execution which could result in further inconsistencies being generated in the following slides even if their contents are perfectly safe. It is like generating errors on top of errors. Therefore, while I am still giving users the option to forcedly continue after an error, I do not think it would be a good idea to do it transparently because it could break the final result.

Feel free to reopen the issue in case your questions are still not addressed.

**Comment by errotu** [comment]
I can confirm that the same error occurs on my installation using Microsoft 365, with PowerPoint at release 16.0.12827.20328 (64-Bit) with PPspliT 1.21 on Win10 (installed in a VirtualBox).

**Comment by maxonthegit** [comment]
There is a small difference in the minor number of the PowerPoint release I am using, but I doubt this is really relevant. In addition, I am using the 32-bit version of Microsoft 365 but, again, usage of the add-in should not be impaired on the 64-bit version.

Instead, as indicated in the [usage instructions](PPspliT-howto.pdf), I am more inclined to thinking that VirtualBox is interfering with clipboard usage: this may indeed happen because of the guest additions. In some cases I have been observing unexpected behaviors while VirtualBox was running, even when PowerPoint was executed on the host.

My advice:
* Try again after [disabling the shared clipboard](https://www.virtualbox.org/manual/ch03.html#settings-general-advanced) in VirtualBox
* Use PowerPoint on the host, preferably while VirtualBox is _not_ running

Finally, I am not seeing any issues while attempting to split your sample presentation. Starting with an empty slide is a very common and covered condition.

**Comment by errotu** [comment]
Thanks a lot for your help! You're right. I was a problem with VirtualBox's shared clipboard. After disabling it, PPspliT worked like a charm. Once again, thanks a lot for your great work!
