### ISSUE TITLE
Slides are assigned a transition effect after splitting

### ISSUE THREAD

**Issue by linguax-gc** [maxonthegit/PPspliT#6]
Thanks for your add-in, it works great.

This is a minor issue I encountered. Whenever I split a presentation, it seems the process adds transitions to the ppt file (specifically the Cut transition, which doesn't show any special effect when using PowerPoint). Then, somehow, it is later preserved when I save the file as pdf and show it in fullscreen, which appears like a checkerboard transition. 

I haven't found any mention to it or any way to solve it. So far the only thing I can do is select all slides and change the transition setting to None. Which is not an important thing, but I have fogotten several times and found out when showing the presentation.

Any ideas? Thanks again.

PS: I'm using v1.23 and Office Professional Plus 2019.

**Comment by maxonthegit** [comment]
Thank you very much for your appreciation and for reporting this (minor) issue.
This has been fixed in release 1.24, which has just been published.

Concerning the fact that you still see the animation in the final PDF, I am not really sure about why this is happening: I am assuming PowerPoint's export to PDF function is not able to keep such transitions in the PDF, although the file format does indeed support them (see, for example, [this guide](https://helpx.adobe.com/acrobat/using/setting-pdfs-presentation.html#:~:text=Choose%20Tools%20%3E%20Organize%20Pages%20%3E%20More,Transitions%20from%20the%20options%20menu%20.)). On the other hand, Adobe Reader (provided that this is the PDF reader you are using) has a setting among the "Full Screen" options which allows you to apply a predefined transition to all pages when in full screen mode:

![image](https://user-images.githubusercontent.com/771877/99448166-b312a280-291f-11eb-8617-044069ecfb8e.png)

You may want to double check this setting.
