### ISSUE TITLE
Clipboard-related errors while splitting

### ISSUE THREAD

**Issue by LukasWallrich** [maxonthegit/PPspliT#7]
Dear Max,

Thanks a lot for this plugin! Unfortunately, I frequently get "Method 'Copy' of object 'TextRange' failed" errors, even when I am trying to split very simple slides like the test slide attached. I do not think that I have anything running that also accesses the clipboard, and am not sure how to troubleshoot this. Would be grateful for any advice - sometimes, I can still get the add-in to produce helpful output by continuing anyway repeatedly, but it would be wonderful if we could get it to actually work.

![image](https://user-images.githubusercontent.com/60155545/107157744-c90f8c80-697d-11eb-8346-1754e23afa8f.png)

All the best,

Lukas
[Dummy.pptx](https://github.com/maxonthegit/PPspliT/files/5939845/Dummy.pptx)

**Comment by LukasWallrich** [comment]
I now experimented with your source code and managed to get it to work when I add an error handler that just calls copy again until it works, adding a brief wait if necessary (on 32 slides that gave me issues before, it never needed more than 10 attempts). Clearly, that shows that the issue is with the clipboard, and thus most likely with my machine, even though I still have no idea why - but maybe such an option would increase the robustness of the add-in?

In case you are interested, I added the following code (with very limited VBA skills, so there might be a much easier way to do this):

```
Private Declare PtrSafe Function WaitMessage Lib "user32" () As Long

Public Sub Wait(Seconds As Double)
    Dim endtime As Double
    endtime = DateTime.Timer + Seconds
    Do
        WaitMessage
        DoEvents
    Loop While DateTime.Timer < endtime
End Sub

'Then inside copyParagraph

TryAgain:
On Error GoTo Oops


    p2.Copy

Oops:
    
    error_count = error_count + 1
    
    If error_count < 5 Then Resume TryAgain
       
    Wait (1)
     
     If error_count < 10 Then Resume TryAgain
```

And something very similar inside applyEffect, where s.Shapes.Paste regularly failed.

**Comment by maxonthegit** [comment]
Hi @LukasWallrich!

As you have already figured out, and as documented in the [PPspliT howto](https://github.com/maxonthegit/PPspliT/blob/master/PPspliT-howto.pdf), any pieces of software that interact with the system clipboard during the split process may cause the latter to fail.

There are reasons for requiring copy-paste operations during the split. As animations in a slide are processed, shapes may be subject to opposite (entry/exit) effects. In principle, processing of these effects may be accomplished without any clipboard usage by:
* creating as many duplicates of a slide as the animation steps and
* deleting shapes in excess (i.e., that are meant to appear at a future animation step or to disappear at a preceding animation step) from each duplicate slide.

In order to reduce the number of required deletions, which may be quadratic in an average case, PPspliT adopts a slightly different approach: although it still creates a duplicate slide for each (applicable) animation effect, shapes are incrementally added (entry effect) or deleted (exit effect) starting from the state of the last processed animation step. Shape "addition" requires a copy-paste cycle from the original slide to preserve (almost) all the shape attributes.

Several types of software may cause unintended interference with the system clipboard. So far the following are known:
* In #3 the shared clipboard of VirtualBox is confirmed to be one. [Disabling it](https://www.virtualbox.org/manual/ch03.html#settings-general-advanced) is a suggested workaround.
* Another user has confirmed that the clipboard history function of Windows 10 is also a potential cause. Also in this case, [disabling it](https://www.howtogeek.com/671222/how-to-enable-and-use-clipboard-history-on-windows-10/) may help.

None of the aforementioned features is active on my machine and, in fact, I could successfully split your presentation.

With your clever workaround you have definitely hit the point: some of the aforementioned pieces of software apparently delay copy-paste operations causing them to fail or the clipboard to contain garbage before their tasks are actually completed. Although your code snippet is likely already minimal, I would refrain from including it in the official branch because it strongly depends on event timing (i.e., how fast the host machine is, how does the system scheduler order these tasks, etc.): this is not a very good programming practice and, in general, may bring about further unpredictable effects, although it may work "more often". I would still like to thank you for sharing the snippet, as it can still serve as a future reference.

Other options are still welcome, but for the moment I think the best that can be done is to be aware of the problem and keep populating the above list of known interfering pieces of software.

**Comment by LukasWallrich** [comment]
Thanks a lot for clarifying this, Max! The Windows clipboard history might indeed be the culprit; I will experiment. I will also keep my 'robust' version of the code in my back pocket, but your reasons for not including it make a lot of sense.

**Comment by jdarch** [comment]
Windows 10 clipboard history is also causing PPspliT to stop working for me. As soon as I turned Windows clipboard history off, PPspliT worked again.

Is this something you could look at?

**Comment by maxonthegit** [comment]
Hi @jdarch,

thank you for adding your report. As discussed in [this comment](https://github.com/maxonthegit/PPspliT/issues/7#issuecomment-780845903), I am not 100% sure about the true cause, but it is not unlikely that clipboard history might introduce a little delay in handling system clipboard entries, thus causing a race condition in which PPspliT may sometimes attempt to access invalid clipboard contents. The bad news is that there is not much that can be done to safely cope with this:
* one option would be to introduce a delay before each clipboard-related operation, which would result in a massive slowdown of the split process;
* another option would be to re-use @LukasWallrich's code snippet, which in case of failure repeats clipboard attempts a number of times before giving up.

As side thoughts, with the current design of PPspliT clipboard operations cannot be avoided altogether (and there were reasons for choosing this design). On the other hand, based on user reports, few people seem to be suffering from this history-related clipboard problem.

All in all, it is far more viable to turn off clipboard history (at least when PPspliT is about to run) or apply one of the aforementioned workarounds rather than to seek for other fixes that might even worsen the average user experience regardless of the actual presence of clipboard-disturbing factors (admittedly, this might not be the case for @LukasWallrich's snippet).
Sorry, but I'm afraid this resolves in a "won't fix". I am refraining from adjusting the "not an issue" label accordingly because of the few reports received so far, and because (easy) workarounds exist.

**Comment by jdarch** [comment]
Hello @maxonthegit 

thanks for taking the time to reply and explain.

I'm happy to turn off Windows clipboard history when using PPspliT.

(Maybe it happens for me because I'm using quite old hardware?)

I agree that simply turning off Windows 10 clipboard history (which completely fixes the problem for me) is a viable workaround. I thought it worth commenting, as this workaround might be useful to others with the same problem.

Thanks again for providing a really useful tool :¬)

**Comment by maxonthegit** [comment]
No problem @jdarch! :wink:

And, no, this does not just happen with "quite old" hardware: although not extremely up-to-date, my workstation is still fairly recent and well-equipped, yet the issue occurs.

Happy splitting!
