### ISSUE TITLE
MacOS: Flattening an equation with animations does not work

### ISSUE THREAD

**Issue by diego898** [maxonthegit/PPspliT#8]
I have several equations revealed through animations. When I flatten this slide, the resulting slides are all wrong and have extra equation characters everywhere

**Comment by maxonthegit** [comment]
Hi @diego898,

your issue is likely not MacOS-specific. Equally likely, you are using equations in the advanced format that is natively available since PowerPoint 2013. Such equations are knowingly unsupported due to some internal limitations in the ability to process them using Visual Basic for Applications.
As stated in the [list of known limitations](https://github.com/maxonthegit/PPspliT#known-limitations):
> Some functions are knowingly unsupported and may never be implemented:

...

> Text effects applied to paragraphs containing a mixture of standard text and equations in the new native PowerPoint 2013 format (i.e., not Equation Editor objects).

Sorry, but there is not much that I can suggest to deal with this. The only option to make these equations _compatible_ with the add-in would be to:
* move them away from the rest of the text flow, enclosing each of them in a separate text box
* apply animation effects to these text boxes as a whole (i.e., effects should be applied to the shape, not to the enclosed text)

Of course this would require some reworking of your original presentation.
