### ISSUE TITLE
Old release (1.5) mentioned in README.md + Split failures in latest release (1.24)

### ISSUE THREAD

**Issue by osnofas** [maxonthegit/PPspliT#9]
Hi! First of all, thanks for all the work!
Question: both the code and the addin's ribbon say that the version number is 1.24. The readme.md however refers to version 1.5 as outdated. Is the publicly available addin the most updated one?

I ask because I've tried it on a simple animation and it fails. It doesn't use any of the techniques you list as causing it to fail. I get several errors like the one in the screenshot in a single slide. I can provide the PPT if it's useful for you.

![image](https://user-images.githubusercontent.com/13853688/110708481-812c9100-81d9-11eb-8e5d-9d1391a444c0.png)

**Comment by maxonthegit** [comment]
Thank you @osnofas for your appreciation!

Both the published source code and the downloadable installer packages are aligned at the latest 1.24 release (please point out if you have noticed otherwise). This can be checked by looking at the [commit history](https://github.com/maxonthegit/PPspliT/commits/master), the date of the [latest release](https://github.com/maxonthegit/PPspliT/releases) or the [download links](http://www.maxonthenet.altervista.org/ppsplit.php) in my home page.
Release 1.5 mentioned in the README.md is explicitly qualified as _outdated_ and is only there for historical reasons, to remind of a potential fix for an issue that happened a long time ago and had an officially documented workaround, although it is unlikely to occur again. I have slightly emphasized its "old" status further.

Concerning the issue you are experiencing, I understand that it does not fall among any of the [known limitations](https://github.com/maxonthegit/PPspliT#known-limitations). I suggest to double check potential clipboard-related interference as described in [this comment](https://github.com/maxonthegit/PPspliT/issues/7#issuecomment-780845903) of #7. In case this does not still address your problem, you can send a minimal example triggering the problem by e-mail (see my [contacts page](http://www.maxonthenet.altervista.org/contacts.php)).
I am waiting for your feedback before marking the issue as closed.

**Comment by maxonthegit** [comment]
I have looked into the sample slide deck. Indeed, it contains animation effects applied to individual shapes that are part of a composite object (a chart). Although not explicitly documented, this is a knowingly unsupported case.
I have updated the README.md file in commit https://github.com/maxonthegit/PPspliT/commit/e8d1635807243bf94f8c10fe4e1ae8724f5728c2 to reflect this.
As a suggested workaround for the cases in which pieces of a chart need to be displayed incrementally, it is possible to apply proper entry/exit effects to background-colored rectangles overlapped to the chart, which are used as "curtains" that selectively hide or reveal chart areas as required.
This should fully address this issue.
